apiVersion: v1
kind: Pod
metadata:
  namespace: dolos
  name: dolos-rebuild
spec:
  containers:
    - name: dolos-container
      image: us-central1-docker.pkg.dev/comet-7aaf0/comet-ar/dolos:sha-daddf2a
      restartPolicy: Never
      command:
        [
          "bash",
          "-c",
          "dolos",
          "doctor",
          "rebuild-ledger",
          "--config",
          "/etc/dolos.toml",
        ]
      ports:
        - containerPort: 50051

      volumeMounts:
        - name: data-volume
          mountPath: /var/data
          readOnly: false

      resources:
        requests:
          memory: "1Gi"
          cpu: "2"
        limits:
          memory: "1Gi"
          cpu: "2"

  # volumeClaimTemplates:
  #   - metadata:
  #       name: data-volume
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 375Gi
