apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: dolos-app
  name: data-volume-dolos-app-0
  namespace: dolos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: hyperdisk-balanced
