apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dolos
  name: dolos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dolos-app

  updateStrategy:
    type: RollingUpdate

  serviceName: dolos-svc

  template:
    metadata:
      labels:
        app: dolos-app
    spec:
      nodeSelector:
        cloud.google.com/compute-class: "Performance"
        cloud.google.com/machine-family: "c3"
      containers:
        - name: dolos-container
          image: us-central1-docker.pkg.dev/comet-7aaf0/comet-ar/dolos:sha-91e83e1
          tty: true
          ports:
            - containerPort: 50051

          volumeMounts:
            - name: data-volume
              mountPath: /var/data
              readOnly: false

          resources:
            requests:
              memory: "2.5Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "1"

  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 400Gi
        storageClassName: hyperdisk-balanced
