apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dolos
  name: dolos-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dolos-app

  updateStrategy:
    type: RollingUpdate

  serviceName: dolos-svc

  template:
    metadata:
      labels:
        app: dolos-app
    spec:
      containers:
        - name: dolos-container
          image: us-central1-docker.pkg.dev/comet-7aaf0/comet-ar/dolos:sha-daddf2a
          ports:
            - containerPort: 50051

          volumeMounts:
            - name: data-volume
              mountPath: /var/data
              readOnly: false

          resources:
            requests:
              memory: "1Gi"
              cpu: "2"
            limits:
              memory: "1Gi"
              cpu: "2"

      initContainers:
        - name: dolos-init
          image: us-central1-docker.pkg.dev/comet-7aaf0/comet-ar/dolos:sha-daddf2a
          command: ["/bin/sh", "-c"]
          args:
            [
              "dolos doctor rebuild-ledger --config /etc/dolos.toml && echo 'Ledger rebuilt successfully!' || echo 'Failed to rebuild ledger'",
            ]
          volumeMounts:
            - name: data-volume
              mountPath: /var/data
              readOnly: false
          resources:
            requests:
              memory: "1Gi"
              cpu: "2"
            limits:
              memory: "1Gi"
              cpu: "2"

  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 375Gi
