apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dolos
  name: dolos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dolos-app

  updateStrategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: dolos-app
    spec:
      containers:
        - name: dolos-container
          image: us-central1-docker.pkg.dev/comet-7aaf0/comet-ar/dolos:sha-c9061b1
          command: ["dolos", "daemon", "--config", "/etc/dolos.toml"]
          ports:
            - containerPort: 50051

          volumeMounts:
            - name: data-volume
              mountPath: /var/data
              readOnly: false

            - name: config-volume
              mountPath: /etc/dolos.toml
              subPath: dolos.toml

          resources:
            requests:
              memory: "8Gi"
              cpu: "8"
            limits:
              memory: "8Gi"
              cpu: "8"

      volumes:
        - name: config-volume
          configMap:
            name: dolos-config

  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 250Gi
